/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminTabbar: typeof import('./src/components/AdminTabbar.vue')['default']
    AgentPicker: typeof import('./src/components/teacher/AgentPicker.vue')['default']
    AppConfirm: typeof import('./src/components/AppConfirm.vue')['default']
    ApplicationCard: typeof import('./src/components/admin/ApplicationCard.vue')['default']
    ApplicationDetailDialog: typeof import('./src/components/admin/ApplicationDetailDialog.vue')['default']
    CityPicker: typeof import('./src/components/teacher/CityPicker.vue')['default']
    DeactivatePopup: typeof import('./src/components/teacher/profile/DeactivatePopup.vue')['default']
    FeesPopup: typeof import('./src/components/teacher/profile/FeesPopup.vue')['default']
    NotificationsPopup: typeof import('./src/components/teacher/profile/NotificationsPopup.vue')['default']
    OrderSheet: typeof import('./src/components/teacher/OrderSheet.vue')['default']
    PasswordPopup: typeof import('./src/components/teacher/profile/PasswordPopup.vue')['default']
    ProfileEditPopup: typeof import('./src/components/teacher/profile/ProfileEditPopup.vue')['default']
    RecommendList: typeof import('./src/components/teacher/RecommendList.vue')['default']
    ResumeLibrary: typeof import('./src/components/teacher/profile/ResumeLibrary.vue')['default']
    ReviewPopup: typeof import('./src/components/admin/ReviewPopup.vue')['default']
    ReviewsPopup: typeof import('./src/components/teacher/profile/ReviewsPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherMatchPopup: typeof import('./src/components/admin/TeacherMatchPopup.vue')['default']
    TeacherTabbar: typeof import('./src/components/TeacherTabbar.vue')['default']
    TrialFailedPopup: typeof import('./src/components/admin/TrialFailedPopup.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
