"""initial schema

Revision ID: a9a54481a950
Revises: 
Create Date: 2026-09-02 12:51:30.773323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a54481a950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信 OpenID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='教员姓名'),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False, comment='性别'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='手机号'),
    sa.Column('wechat_id', sa.String(length=50), nullable=False, comment='微信号'),
    sa.Column('school', sa.String(length=50), nullable=False, comment='毕业/就读院校'),
    sa.Column('is_985_211', sa.Boolean(), nullable=True, comment='是否 985/211'),
    sa.Column('is_985', sa.Boolean(), nullable=True, comment='是否 985 院校'),
    sa.Column('is_211', sa.Boolean(), nullable=True, comment='是否 211 院校'),
    sa.Column('is_double_first_class', sa.Boolean(), nullable=True, comment='是否双一流院校'),
    sa.Column('major', sa.String(length=50), nullable=True, comment='专业'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='年级'),
    sa.Column('highlights', sa.Text(), nullable=True, comment='优势标签'),
    sa.Column('lng', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='常驻地经度'),
    sa.Column('lat', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='常驻地纬度'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.String(length=50), nullable=False, comment='中介/机构名称'),
    sa.Column('invite_code', sa.String(length=20), nullable=False, comment='专属邀请码'),
    sa.Column('contact_wechat', sa.String(length=50), nullable=False, comment='中介联系微信号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='归属租户 ID'),
    sa.Column('raw_id', sa.String(length=50), nullable=False, comment='上游原始编号'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='原始微信聊天文本'),
    sa.Column('grade_subject', sa.String(length=50), nullable=False, comment='年级科目'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='教员要求'),
    sa.Column('price_total', sa.String(length=50), nullable=False, comment='原始课酬文本'),
    sa.Column('base_price', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='单次标准课酬'),
    sa.Column('weekly_frequency', sa.Integer(), nullable=True, comment='每周上课次数'),
    sa.Column('is_summer_vacation', sa.Boolean(), nullable=True, comment='是否寒暑假单'),
    sa.Column('calculated_info_fee', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='全额信息费'),
    sa.Column('deposit_amount', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='锁定定金'),
    sa.Column('balance_amount', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='需补齐尾款'),
    sa.Column('exact_address', sa.String(length=255), nullable=True, comment='真实门牌号与联系方式（尾款解锁）'),
    sa.Column('parent_phone', sa.String(length=20), nullable=True, comment='家长联系电话（尾款解锁）'),
    sa.Column('fuzzy_address', sa.String(length=100), nullable=False, comment='模糊展示地址'),
    sa.Column('subway_remark', sa.String(length=100), nullable=True, comment='交通补丁'),
    sa.Column('lng', sa.DECIMAL(precision=10, scale=6), nullable=False, comment='订单地理编码经度，不做人工偏移'),
    sa.Column('lat', sa.DECIMAL(precision=10, scale=6), nullable=False, comment='订单地理编码纬度，不做人工偏移'),
    sa.Column('status', sa.Enum('recruiting', 'trial_in_progress', 'completed', 'archived', 'pending_deposit', 'pending_approval', 'pending_balance', name='orderstatus'), nullable=True, comment='订单状态'),
    sa.Column('selected_teacher_id', sa.Integer(), nullable=True, comment='当前被选中的教员 ID'),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_id', name='uk_tenant_raw')
    )
    op.create_index('idx_raw_id', 'orders', ['raw_id'], unique=False)
    op.create_index('idx_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('teacher_resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False, comment='简历名称'),
    sa.Column('teaching_subjects', sa.String(length=120), nullable=False, comment='可授科目'),
    sa.Column('teaching_grades', sa.String(length=120), nullable=False, comment='可授年级'),
    sa.Column('experience', sa.Text(), nullable=False, comment='家教经历'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='个人优势'),
    sa.Column('availability', sa.String(length=120), nullable=True, comment='可授课时间'),
    sa.Column('expected_rate', sa.String(length=50), nullable=True, comment='期望课酬'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='默认简历'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teacher_resume', 'teacher_resumes', ['teacher_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shortlisted', 'trial_in_progress', 'deposit_paid', 'balance_paid', 'rejected', 'refunded', name='applicationstatus'), nullable=True, comment='投递状态'),
    sa.Column('proposed_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='教员报价（自带价订单时填写）'),
    sa.Column('applied_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('shortlisted_at', sa.TIMESTAMP(), nullable=True, comment='被选中时间'),
    sa.Column('deposit_paid_at', sa.TIMESTAMP(), nullable=True, comment='支付定金时间'),
    sa.Column('balance_paid_at', sa.TIMESTAMP(), nullable=True, comment='补齐尾款时间'),
    sa.Column('rejected_at', sa.TIMESTAMP(), nullable=True, comment='被拒时间'),
    sa.Column('refunded_at', sa.TIMESTAMP(), nullable=True, comment='退款时间'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['teacher_resumes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'order_id', name='uk_teacher_order')
    )
    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='涉及金额'),
    sa.Column('type', sa.Enum('deposit_in', 'balance_in', 'refund_out', 'forfeit', name='financialtype'), nullable=False, comment='交易类型'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_records')
    op.drop_table('applications')
    op.drop_index('idx_teacher_resume', table_name='teacher_resumes')
    op.drop_table('teacher_resumes')
    op.drop_index('idx_tenant_status', table_name='orders')
    op.drop_index('idx_raw_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('tenants')
    op.drop_table('teachers')
    # ### end Alembic commands ###
